before_script:
  - apt-get update -qq
  - apt-get install -qq ssh sshpass

deploy_staging:
  environment:
    name: staging
    url: $HOST
  script:
    - script -qc "sshpass -p $PASSWORD ssh -p $PORT $USERNAME@$HOST /home/$USERNAME/scripts/mwenclubhouse-discord.sh"
  only:
    - main