deploy_staging:
  stage: deploy
  image: ubuntu:latest
  environment: Staging
  script:
    - apt-get update -qq
    - apt-get install -qq ssh sshpass
    - sshpass -V
    - echo $USERNAME
    - export SSHPASS=$PASSWORD
    - sshpass -e ssh -p $PORT $USERNAME@$HOST '/home/mwen/scripts/mwenclubhouse-discord.sh'
  only:
    - main
