before_script:
  - apt-get update -qq
  - apt-get install -qq ssh sshpass

deploy_staging:
  environment:
    name: staging
    url: $HOST
  script:
    - sshpass -p "$PASSWORD" ssh -p $PORT $USERNAME@$HOST "./scripts/mwenclubhouse-discord.sh && exit"
  only:
    - main